### PR TITLE
added images section of the workshop to the website

### PR DESCRIPTION
**Pull request by yash-kedia**

### CODE REVIEW

**Comment by Ankk98** [comment]
First, we need a navbar, once it is completed we will add these sections.
Also, keep about section above other sections.

**Comment by im-gozmit** [comment]
@yash-kedia  are you still working on this, if so then please do the changes suggested by @Ankk98.

**Comment by yash-kedia** [comment]
he suggested me to build a navbar first

i dont know what all items to include in the navbar there are very few
items just now
like home about and events phots

**Comment by Ankk98** [comment]
@yash-kedia
Navbar is constructed.
Now you can send your changes for gallery section.

**Pull request closed without merging**
