### PR TITLE
(ci) add Lighthouse CI GitHub Action

### PR DESCRIPTION
**Pull request by LeoAlvarenga**
Issue #2 Add Lighthouseci to ci.yml

Sorry for the long time to resolve this, i had some difficulties managing the commits and repos from the fork and the origin repo.

Please, confirm if this was what you asked on the issue.

### CODE REVIEW

**Comment by LeoAlvarenga** [comment]
Hey guys, i just did the lighthouseci works adding a CI job and a new file, i dont get why those failures on the checks..., can someone let me know if i did something wrong?

**Comment by humancalico** [comment]
@LeoAlvarenga Can you try pushing an empty commit?

**Comment by LeoAlvarenga** [comment]
@humancalico i just tried it, but the netlify checks fails, i dont get why, because i didnt made any changes on the site files

**Comment by LeoAlvarenga** [comment]
the log from netlify

> Cannot find module 'rollup-plugin-glob'
8:26:47 PM: Require stack:
8:26:47 PM: - /opt/build/repo/rollup.config.js
8:26:47 PM: - /opt/build/repo/node_modules/sapper/dist/create_manifest_data.js
8:26:47 PM: - /opt/build/repo/node_modules/sapper/dist/build.js
8:26:47 PM: - /opt/build/repo/node_modules/sapper/dist/cli.js
8:26:47 PM: - /opt/build/repo/node_modules/sapper/sapper

**Comment by humancalico** [comment]
Hmm. There might be a problem in the Netlify configuration. Anyway thanks for the PR @LeoAlvarenga 

cc @aayushmau5 @im-prakher

**Comment by LeoAlvarenga** [comment]
Ok! Thanks for accept the PR!

**Comment by aayushmau5** [comment]
Yeah, it was because of outdated node modules. It's fixed now. I guess, push a demo PR to run the check again.

**Comment by LeoAlvarenga** [comment]
I think it's all set now

**Pull request merged**
