### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by humancalico**
Deployed at https://jodc-website.vercel.app/

### CODE REVIEW

**Comment by weirdwiz** [comment]
@im-prakher @Ankurk99 PTAL

**Review by weirdwiz — CHANGES_REQUESTED** [review]

**Comment by Ankurk99** [comment]
Looks good to me.

**Review by weirdwiz — APPROVED** [review]
LGTM

**Review by anmol27katyani — COMMENTED** [review]
I am not sure but Team page is not accurate

**Review by aaryanporwal — APPROVED** [review]

**Comment by im-prakher** [comment]
Good work guys!!
Few suggestions-
- Use grid or flexbox for cards in the team section rather than scrolling cards horizontally
- I like the flip effect but when hovering on the _Click on JODC !_ text, my mouse pointer changes to text cursor
- You can replace _Click on JODC !_ text with _Click here_
-  Use retina image for JODC mascot (Check this out- [css techniques for retina displays](https://www.sitepoint.com/css-techniques-for-retina-displays/))

**Review by im-prakher — APPROVED** [review]

**Comment by weirdwiz** [comment]
@JIITODC/website-maintainers is it ready for merge? The team members can make subsequent pull requests, to add their info

**Comment by AarKiMos** [comment]
Actually not yet @weirdwiz , some major changes are yet to be made to team page

**Comment by weirdwiz** [comment]
@AarKiMos oh cool, thanks for the info

**Review by aaryanporwal — APPROVED** [review]

**Pull request merged**
