### PR TITLE
Updated index.html to be more responsive

### PR DESCRIPTION
**Pull request by Ankurk99**
**REFERENCING ISSUE #88**

## Fixes applied
- Added Home icon in navbar
- Added interactive font awesome icons in home section
- Fixed problem with the position of hamburger menu in smaller screens (with width less than 1300px)
- Displayed Menu indication with hamburger icon in smaller screens
- fixed linting errors
## Screenshots
Home Option in navbar
navbar
Interactive font-awesome icons in home option
font-awesome
Before edit: Navbar in mobile view not correctly aligned 
screenshot from 2018-11-03 23-11-03
After edit: Navbar right aligned with Menu indication
menu

### CODE REVIEW

**Comment by triptishukla** [comment]
good work!

**Comment by Ankurk99** [comment]
Please also merge issue #92 for the changes to take effect correctly as it contains the css file with reference to this html file

**Comment by Ankurk99** [comment]
Also it doesn't contain the Events section which includes event timeline so please make changes as per issue #3 and include that code in it.

**Comment by Ankurk99** [comment]
Added timeline again refer ISSUE #93

**Pull request merged**
