### PR TITLE
Add information about @weirdwiz

### PR DESCRIPTION
**Pull request by weirdwiz**

### CODE REVIEW

**Comment by humancalico** [comment]
@weirdwiz Can you uninstall Vercel from the org? I don't have enough permissions to do that

**Comment by weirdwiz** [comment]
> Personal accounts on Vercel can only be connected to personal accounts on GitHub, not organizations.
Please remove the Git Integration from your GitHub organization by clicking the button below.

I got this

**Comment by weirdwiz** [comment]
I'll try creating a team

**Comment by humancalico** [comment]
Does this work? https://vercel.com/docs/git-integrations/vercel-for-github#uninstall-vercel

**Comment by weirdwiz** [comment]
@humancalico are there any ENV variables?

Also, I've kept the default Sapper build command, and output directory are these fine?

**Comment by humancalico** [comment]
Ohh no. We had to get rid off Vercel because it was paid for orgs so it's hosted on Netlify now. I was asking to uninstall it from the Applications since the checks are failing because of it.

**Comment by weirdwiz** [comment]
Wow, I read install instead of uninstall. 
Done

**Comment by humancalico** [comment]
Hehe. Thanks!

**Comment by humancalico** [comment]
Also can you add a photo too? 😅

**Pull request merged**
